// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Book struct {
	ID      string  `json:"id"`
	Author  string  `json:"author"`
	Isbn    string  `json:"isbn"`
	Title   string  `json:"title"`
	Summary *string `json:"summary,omitempty"`
}

type BookFilters struct {
	ID *string `json:"id,omitempty"`
}

type BookInput struct {
	Author  string  `json:"author"`
	Isbn    string  `json:"isbn"`
	Title   string  `json:"title"`
	Summary *string `json:"summary,omitempty"`
}
